# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: r2bus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0br2bus.proto\x12\x05r2bus\"L\n\x03\x41\x63k\x12\x1d\n\x06status\x18\x01 \x01(\x0e\x32\r.r2bus.Status\x12&\n\x0coriginal_msg\x18\x02 \x01(\x0e\x32\x10.r2bus.MessageId\"\x17\n\x04Ping\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x17\n\x04Pong\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x1e\n\tHeartbeat\x12\x11\n\tuptime_ms\x18\x01 \x01(\r\"O\n\x0fPsiColorRequest\x12\x0b\n\x03red\x18\x01 \x01(\r\x12\r\n\x05green\x18\x02 \x01(\r\x12\x0c\n\x04\x62lue\x18\x03 \x01(\r\x12\x12\n\nbrightness\x18\x04 \x01(\r\"L\n\x10ServoMoveCommand\x12\r\n\x05servo\x18\x01 \x01(\r\x12\x14\n\x0cposition_deg\x18\x02 \x01(\x02\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\r\".\n\x10ServoHomeCommand\x12\r\n\x05servo\x18\x01 \x01(\r\x12\x0b\n\x03\x61ll\x18\x02 \x01(\x08\"P\n\x10HoloColorRequest\x12\x0b\n\x03red\x18\x01 \x01(\r\x12\r\n\x05green\x18\x02 \x01(\r\x12\x0c\n\x04\x62lue\x18\x03 \x01(\r\x12\x12\n\nbrightness\x18\x04 \x01(\r\"A\n\x13HoloPositionRequest\x12\x13\n\x0b\x61zimuth_deg\x18\x01 \x01(\x02\x12\x15\n\relevation_deg\x18\x02 \x01(\x02\"\x1e\n\x0ePsiMoodRequest\x12\x0c\n\x04mood\x18\x01 \x01(\r\"\x07\n\x05\x45mpty*)\n\x06Status\x12\r\n\tSTATUS_OK\x10\x00\x12\x10\n\x0cSTATUS_ERROR\x10\x01*\xcf\x02\n\tMessageId\x12\x16\n\x12MESSAGE_ID_UNKNOWN\x10\x00\x12\x18\n\x14MESSAGE_ID_ECU_RESET\x10\x01\x12\x13\n\x0fMESSAGE_ID_PING\x10\x02\x12\x13\n\x0fMESSAGE_ID_PONG\x10\x03\x12\x18\n\x14MESSAGE_ID_HEARTBEAT\x10\x04\x12\x1c\n\x18MESSAGE_ID_PSI_COLOR_REQ\x10\x05\x12\x1d\n\x19MESSAGE_ID_SERVO_MOVE_CMD\x10\x06\x12\x1d\n\x19MESSAGE_ID_SERVO_HOME_CMD\x10\x07\x12\x1d\n\x19MESSAGE_ID_HOLO_COLOR_REQ\x10\x08\x12 \n\x1cMESSAGE_ID_HOLO_POSITION_REQ\x10\t\x12\x1b\n\x17MESSAGE_ID_PSI_MOOD_REQ\x10\n\x12\x12\n\x0eMESSAGE_ID_ACK\x10\x7f\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'r2bus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=579
  _STATUS._serialized_end=620
  _MESSAGEID._serialized_start=623
  _MESSAGEID._serialized_end=958
  _ACK._serialized_start=22
  _ACK._serialized_end=98
  _PING._serialized_start=100
  _PING._serialized_end=123
  _PONG._serialized_start=125
  _PONG._serialized_end=148
  _HEARTBEAT._serialized_start=150
  _HEARTBEAT._serialized_end=180
  _PSICOLORREQUEST._serialized_start=182
  _PSICOLORREQUEST._serialized_end=261
  _SERVOMOVECOMMAND._serialized_start=263
  _SERVOMOVECOMMAND._serialized_end=339
  _SERVOHOMECOMMAND._serialized_start=341
  _SERVOHOMECOMMAND._serialized_end=387
  _HOLOCOLORREQUEST._serialized_start=389
  _HOLOCOLORREQUEST._serialized_end=469
  _HOLOPOSITIONREQUEST._serialized_start=471
  _HOLOPOSITIONREQUEST._serialized_end=536
  _PSIMOODREQUEST._serialized_start=538
  _PSIMOODREQUEST._serialized_end=568
  _EMPTY._serialized_start=570
  _EMPTY._serialized_end=577
# @@protoc_insertion_point(module_scope)
