#! /bin/bash

set -e
bazel build //dome_motor:dome_motor_install
sudo apt install -y --reinstall $(pwd)/bazel-bin/dome_motor/dome-motor_0.1.0_all.deb
set +e

echo "Dome motor package installed."

PLATFORM=${1:-rp2040}
OUT_DIR="$(dirname "$0")/out"

mkdir -p "$OUT_DIR"

bazel build //firmware:all \
  --platforms=@pico-sdk//bazel/platform:"$PLATFORM" \
  --aspects @pico-sdk//tools:uf2_aspect.bzl%pico_uf2_aspect \
  --output_groups=+pico_uf2_files

find bazel-bin/firmware -name "*.uf2" -exec cp {} "$OUT_DIR/" \;
find bazel-bin/firmware -name "*.elf" -exec cp {} "$OUT_DIR/" \;

echo "Firmware artifacts in $OUT_DIR:"
ls "$OUT_DIR"