/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_HOLOPROJECTOR_HOLOPROJECTOR_PB_H_INCLUDED
#define PB_HOLOPROJECTOR_HOLOPROJECTOR_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _holoprojector_LEDCommand {
    uint32_t r;
    uint32_t g;
    uint32_t b;
    uint32_t brightness;
} holoprojector_LEDCommand;

typedef struct _holoprojector_HoloprojectorCommand {
    float servo1_angle;
    float servo2_angle;
    pb_callback_t led_commands;
} holoprojector_HoloprojectorCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define holoprojector_LEDCommand_init_default    {0, 0, 0, 0}
#define holoprojector_HoloprojectorCommand_init_default {0, 0, {{NULL}, NULL}}
#define holoprojector_LEDCommand_init_zero       {0, 0, 0, 0}
#define holoprojector_HoloprojectorCommand_init_zero {0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define holoprojector_LEDCommand_r_tag           1
#define holoprojector_LEDCommand_g_tag           2
#define holoprojector_LEDCommand_b_tag           3
#define holoprojector_LEDCommand_brightness_tag  4
#define holoprojector_HoloprojectorCommand_servo1_angle_tag 1
#define holoprojector_HoloprojectorCommand_servo2_angle_tag 2
#define holoprojector_HoloprojectorCommand_led_commands_tag 3

/* Struct field encoding specification for nanopb */
#define holoprojector_LEDCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   r,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   g,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   b,                 3) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        4)
#define holoprojector_LEDCommand_CALLBACK NULL
#define holoprojector_LEDCommand_DEFAULT NULL

#define holoprojector_HoloprojectorCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    servo1_angle,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    servo2_angle,      2) \
X(a, CALLBACK, REPEATED, MESSAGE,  led_commands,      3)
#define holoprojector_HoloprojectorCommand_CALLBACK pb_default_field_callback
#define holoprojector_HoloprojectorCommand_DEFAULT NULL
#define holoprojector_HoloprojectorCommand_led_commands_MSGTYPE holoprojector_LEDCommand

extern const pb_msgdesc_t holoprojector_LEDCommand_msg;
extern const pb_msgdesc_t holoprojector_HoloprojectorCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define holoprojector_LEDCommand_fields &holoprojector_LEDCommand_msg
#define holoprojector_HoloprojectorCommand_fields &holoprojector_HoloprojectorCommand_msg

/* Maximum encoded size of messages (where known) */
/* holoprojector_HoloprojectorCommand_size depends on runtime parameters */
#define HOLOPROJECTOR_HOLOPROJECTOR_PB_H_MAX_SIZE holoprojector_LEDCommand_size
#define holoprojector_LEDCommand_size            24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
