/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_R2BUS_R2BUS_PB_H_INCLUDED
#define PB_R2BUS_R2BUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _r2bus_Status {
    r2bus_Status_STATUS_OK = 0,
    r2bus_Status_STATUS_ERROR = 1
} r2bus_Status;

typedef enum _r2bus_MessageId {
    r2bus_MessageId_MESSAGE_ID_UNKNOWN = 0,
    r2bus_MessageId_MESSAGE_ID_ECU_RESET = 1,
    r2bus_MessageId_MESSAGE_ID_PING = 2,
    r2bus_MessageId_MESSAGE_ID_PONG = 3,
    r2bus_MessageId_MESSAGE_ID_HEARTBEAT = 4,
    r2bus_MessageId_MESSAGE_ID_PSI_COLOR_REQ = 5,
    r2bus_MessageId_MESSAGE_ID_SERVO_MOVE_CMD = 6,
    r2bus_MessageId_MESSAGE_ID_SERVO_HOME_CMD = 7,
    r2bus_MessageId_MESSAGE_ID_HOLO_COLOR_REQ = 8,
    r2bus_MessageId_MESSAGE_ID_HOLO_POSITION_REQ = 9,
    r2bus_MessageId_MESSAGE_ID_PSI_MOOD_REQ = 10,
    r2bus_MessageId_MESSAGE_ID_ACK = 127
} r2bus_MessageId;

/* Struct definitions */
typedef struct _r2bus_Ack {
    r2bus_Status status;
    r2bus_MessageId original_msg;
} r2bus_Ack;

typedef PB_BYTES_ARRAY_T(255) r2bus_Ping_payload_t;
typedef struct _r2bus_Ping {
    r2bus_Ping_payload_t payload;
} r2bus_Ping;

typedef PB_BYTES_ARRAY_T(255) r2bus_Pong_payload_t;
typedef struct _r2bus_Pong {
    r2bus_Pong_payload_t payload;
} r2bus_Pong;

typedef struct _r2bus_Heartbeat {
    uint32_t uptime_ms;
} r2bus_Heartbeat;

typedef struct _r2bus_PsiColorRequest {
    uint32_t red;
    uint32_t green;
    uint32_t blue;
    uint32_t brightness;
} r2bus_PsiColorRequest;

typedef struct _r2bus_ServoMoveCommand {
    uint32_t servo;
    float position_deg;
    /* When non-zero, duration_ms carries a raw pulse width request (microseconds). */
    uint32_t duration_ms;
} r2bus_ServoMoveCommand;

typedef struct _r2bus_ServoHomeCommand {
    uint32_t servo;
    bool all;
} r2bus_ServoHomeCommand;

typedef struct _r2bus_HoloColorRequest {
    uint32_t red;
    uint32_t green;
    uint32_t blue;
    uint32_t brightness;
} r2bus_HoloColorRequest;

typedef struct _r2bus_HoloPositionRequest {
    float azimuth_deg;
    float elevation_deg;
} r2bus_HoloPositionRequest;

typedef struct _r2bus_PsiMoodRequest {
    uint32_t mood;
} r2bus_PsiMoodRequest;

typedef struct _r2bus_Empty {
    char dummy_field;
} r2bus_Empty;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _r2bus_Status_MIN r2bus_Status_STATUS_OK
#define _r2bus_Status_MAX r2bus_Status_STATUS_ERROR
#define _r2bus_Status_ARRAYSIZE ((r2bus_Status)(r2bus_Status_STATUS_ERROR+1))

#define _r2bus_MessageId_MIN r2bus_MessageId_MESSAGE_ID_UNKNOWN
#define _r2bus_MessageId_MAX r2bus_MessageId_MESSAGE_ID_ACK
#define _r2bus_MessageId_ARRAYSIZE ((r2bus_MessageId)(r2bus_MessageId_MESSAGE_ID_ACK+1))

#define r2bus_Ack_status_ENUMTYPE r2bus_Status
#define r2bus_Ack_original_msg_ENUMTYPE r2bus_MessageId












/* Initializer values for message structs */
#define r2bus_Ack_init_default                   {_r2bus_Status_MIN, _r2bus_MessageId_MIN}
#define r2bus_Ping_init_default                  {{0, {0}}}
#define r2bus_Pong_init_default                  {{0, {0}}}
#define r2bus_Heartbeat_init_default             {0}
#define r2bus_PsiColorRequest_init_default       {0, 0, 0, 0}
#define r2bus_ServoMoveCommand_init_default      {0, 0, 0}
#define r2bus_ServoHomeCommand_init_default      {0, 0}
#define r2bus_HoloColorRequest_init_default      {0, 0, 0, 0}
#define r2bus_HoloPositionRequest_init_default   {0, 0}
#define r2bus_PsiMoodRequest_init_default        {0}
#define r2bus_Empty_init_default                 {0}
#define r2bus_Ack_init_zero                      {_r2bus_Status_MIN, _r2bus_MessageId_MIN}
#define r2bus_Ping_init_zero                     {{0, {0}}}
#define r2bus_Pong_init_zero                     {{0, {0}}}
#define r2bus_Heartbeat_init_zero                {0}
#define r2bus_PsiColorRequest_init_zero          {0, 0, 0, 0}
#define r2bus_ServoMoveCommand_init_zero         {0, 0, 0}
#define r2bus_ServoHomeCommand_init_zero         {0, 0}
#define r2bus_HoloColorRequest_init_zero         {0, 0, 0, 0}
#define r2bus_HoloPositionRequest_init_zero      {0, 0}
#define r2bus_PsiMoodRequest_init_zero           {0}
#define r2bus_Empty_init_zero                    {0}

/* Field tags (for use in manual encoding/decoding) */
#define r2bus_Ack_status_tag                     1
#define r2bus_Ack_original_msg_tag               2
#define r2bus_Ping_payload_tag                   1
#define r2bus_Pong_payload_tag                   1
#define r2bus_Heartbeat_uptime_ms_tag            1
#define r2bus_PsiColorRequest_red_tag            1
#define r2bus_PsiColorRequest_green_tag          2
#define r2bus_PsiColorRequest_blue_tag           3
#define r2bus_PsiColorRequest_brightness_tag     4
#define r2bus_ServoMoveCommand_servo_tag         1
#define r2bus_ServoMoveCommand_position_deg_tag  2
#define r2bus_ServoMoveCommand_duration_ms_tag   3
#define r2bus_ServoHomeCommand_servo_tag         1
#define r2bus_ServoHomeCommand_all_tag           2
#define r2bus_HoloColorRequest_red_tag           1
#define r2bus_HoloColorRequest_green_tag         2
#define r2bus_HoloColorRequest_blue_tag          3
#define r2bus_HoloColorRequest_brightness_tag    4
#define r2bus_HoloPositionRequest_azimuth_deg_tag 1
#define r2bus_HoloPositionRequest_elevation_deg_tag 2
#define r2bus_PsiMoodRequest_mood_tag            1

/* Struct field encoding specification for nanopb */
#define r2bus_Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, UENUM,    original_msg,      2)
#define r2bus_Ack_CALLBACK NULL
#define r2bus_Ack_DEFAULT NULL

#define r2bus_Ping_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           1)
#define r2bus_Ping_CALLBACK NULL
#define r2bus_Ping_DEFAULT NULL

#define r2bus_Pong_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           1)
#define r2bus_Pong_CALLBACK NULL
#define r2bus_Pong_DEFAULT NULL

#define r2bus_Heartbeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,         1)
#define r2bus_Heartbeat_CALLBACK NULL
#define r2bus_Heartbeat_DEFAULT NULL

#define r2bus_PsiColorRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   red,               1) \
X(a, STATIC,   SINGULAR, UINT32,   green,             2) \
X(a, STATIC,   SINGULAR, UINT32,   blue,              3) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        4)
#define r2bus_PsiColorRequest_CALLBACK NULL
#define r2bus_PsiColorRequest_DEFAULT NULL

#define r2bus_ServoMoveCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    position_deg,      2) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       3)
#define r2bus_ServoMoveCommand_CALLBACK NULL
#define r2bus_ServoMoveCommand_DEFAULT NULL

#define r2bus_ServoHomeCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo,             1) \
X(a, STATIC,   SINGULAR, BOOL,     all,               2)
#define r2bus_ServoHomeCommand_CALLBACK NULL
#define r2bus_ServoHomeCommand_DEFAULT NULL

#define r2bus_HoloColorRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   red,               1) \
X(a, STATIC,   SINGULAR, UINT32,   green,             2) \
X(a, STATIC,   SINGULAR, UINT32,   blue,              3) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        4)
#define r2bus_HoloColorRequest_CALLBACK NULL
#define r2bus_HoloColorRequest_DEFAULT NULL

#define r2bus_HoloPositionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    azimuth_deg,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    elevation_deg,     2)
#define r2bus_HoloPositionRequest_CALLBACK NULL
#define r2bus_HoloPositionRequest_DEFAULT NULL

#define r2bus_PsiMoodRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mood,              1)
#define r2bus_PsiMoodRequest_CALLBACK NULL
#define r2bus_PsiMoodRequest_DEFAULT NULL

#define r2bus_Empty_FIELDLIST(X, a) \

#define r2bus_Empty_CALLBACK NULL
#define r2bus_Empty_DEFAULT NULL

extern const pb_msgdesc_t r2bus_Ack_msg;
extern const pb_msgdesc_t r2bus_Ping_msg;
extern const pb_msgdesc_t r2bus_Pong_msg;
extern const pb_msgdesc_t r2bus_Heartbeat_msg;
extern const pb_msgdesc_t r2bus_PsiColorRequest_msg;
extern const pb_msgdesc_t r2bus_ServoMoveCommand_msg;
extern const pb_msgdesc_t r2bus_ServoHomeCommand_msg;
extern const pb_msgdesc_t r2bus_HoloColorRequest_msg;
extern const pb_msgdesc_t r2bus_HoloPositionRequest_msg;
extern const pb_msgdesc_t r2bus_PsiMoodRequest_msg;
extern const pb_msgdesc_t r2bus_Empty_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define r2bus_Ack_fields &r2bus_Ack_msg
#define r2bus_Ping_fields &r2bus_Ping_msg
#define r2bus_Pong_fields &r2bus_Pong_msg
#define r2bus_Heartbeat_fields &r2bus_Heartbeat_msg
#define r2bus_PsiColorRequest_fields &r2bus_PsiColorRequest_msg
#define r2bus_ServoMoveCommand_fields &r2bus_ServoMoveCommand_msg
#define r2bus_ServoHomeCommand_fields &r2bus_ServoHomeCommand_msg
#define r2bus_HoloColorRequest_fields &r2bus_HoloColorRequest_msg
#define r2bus_HoloPositionRequest_fields &r2bus_HoloPositionRequest_msg
#define r2bus_PsiMoodRequest_fields &r2bus_PsiMoodRequest_msg
#define r2bus_Empty_fields &r2bus_Empty_msg

/* Maximum encoded size of messages (where known) */
#define R2BUS_R2BUS_PB_H_MAX_SIZE                r2bus_Ping_size
#define r2bus_Ack_size                           4
#define r2bus_Empty_size                         0
#define r2bus_Heartbeat_size                     6
#define r2bus_HoloColorRequest_size              24
#define r2bus_HoloPositionRequest_size           10
#define r2bus_Ping_size                          258
#define r2bus_Pong_size                          258
#define r2bus_PsiColorRequest_size               24
#define r2bus_PsiMoodRequest_size                6
#define r2bus_ServoHomeCommand_size              8
#define r2bus_ServoMoveCommand_size              17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
